# -*- coding: utf-8 -*-
"""Ejercicios 1  y 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMYDF-0BlGB56cPYj1nZOkrKrhJDvEqD
"""

'''
Clase:        Fase de fortalecimiento lógico
Tema:         operadores arismeticos
Ejercicio:    1.3.1. Automatizando el cálculo de la propina
Descripción:  Pide al usuario el total de una cuenta y el porcentaje de propina
(por ejemplo, 10%, 15%, 20%). Calcula y muestra en pantalla el total
a pagar.

Autor:        Edwin Eduardo Hernandez Lopez
Fecha:        2025-05-21
Estado:       Terminado
'''


total = int(input('Cuanto gastaste?'))

propina = 100 / 10

#print(propina)
#print(total)
print(total + propina)

'''
Clase:        Fase de fortalecimiento lógico
Tema:         Concatenar texto
Ejercicio:    1.3.2. Generador del correo de Key
Descripción:  Solicita al usuario su nombre completo (asume dos nombres y
dos apellidos). Luego, el programa generará, su correo con el
formato:
• primer_nombre.primer_apellido@keyinstitute.edu.sv

Autor:        Edwin Eduardo Hernandez Lopez
Fecha:        2025-05-21
Estado:       Terminado
'''

nombre = input('Escribe tus nombres')
apellido = input('Escribe tus apellidos')
primer_nombre = nombre.split()[0]
primer_apellido = apellido.split()[0]
print(f"el correo que se debe asignar al usuario ingresado es: {primer_nombre}.{primer_apellido}@keyinstitute.edu.sv")

'''
Clase:        Fase de fortalecimiento lógico 02
Tema:         Condicionales
Ejercicio:    2.3.1. Contraseña segura
Descripción:  Solicita una cadena de texto que representa una contraseña, y verifica si la contraseña
cumple con las siguientes condiciones: tener al menos 8 caracteres, un número y una
mayúscula.

Autor:        Edwin Eduardo Hernandez Lopez
Fecha:        2025-05-21
Estado:       Terminado
'''

contra = 'HolaAmigos123'

mayus = False
num = False


for caracter in contra:
  if caracter.isupper():
    mayus = True
  elif caracter.isdigit():
    num = True

if mayus == True and num == True and len(contra) >= 8:
  print('contraseña valida')
else:
  print('contraseña invalida')

'''
Clase:        Fase de fortalecimiento lógico 02
Tema:         Condicionales
Ejercicio:    22.3.2. Cálculo de impuesto
Descripción:  Desarrollar un programa en Python que permita calcular el impuesto que debe pagar
un usuario por el consumo de energía. El cálculo debe realizarse basado en la siguiente
tabla.

Autor:        Edwin Eduardo Hernandez Lopez
Fecha:        2025-05-21
Estado:       Terminado
'''

unidades = 101

if unidades <= 100:
  print('no hay impuesto')
elif unidades >= 101 and unidades < 200:
  print(unidades * 0.5)
elif unidades >= 201 and unidades < 300:
  print(unidades * 0.7)
else:
  print(unidades * 0.9)